
# weapon_dict = {
#     '52gal': '.52ガロン',
#     '96gal': '.96ガロン',
#     '96gal_deco': '.96ガロンデコ',
#     'nzap85': 'N-ZAP85',
#     'nzap89': 'N-ZAP89',
#     'momiji': 'もみじシューター',
#     'wakaba': 'わかばシューター',
#     'sharp': 'シャープマーカー',
#     'sharp_neo': 'シャープマーカーネオ',
#     'jetsweeper': 'ジェットスイーパー',
#     'jetsweeper_custom': 'ジェットスイーパーカスタム',
#     'sshooter': 'スプラシューター',
#     'sshooter_collabo': 'スプラシューターコラボ',
#     'spaceshooter': 'スペースシューター',
#     'spaceshooter_collabo': 'スペースシューターコラボ',
#     # 'heroshooter_replica': 'ヒーローシューター レプリカ',
#     'prime': 'プライムシューター',
#     'prime_collabo': 'プライムシューターコラボ',
#     'promodeler_mg': 'プロモデラーMG',
#     'promodeler_rg': 'プロモデラーRG',
#     'bottlegeyser': 'ボトルガイザー',
#     'bold': 'ボールドマーカー',
#     'bold_neo': 'ボールドマーカーネオ',
#     'rapid_elite': 'Rブラスターエリート',
#     'rapid_elite_deco': 'Rブラスターエリートデコ',
#     'sblast92': 'S-BLAST92',
#     'clashblaster': 'クラッシュブラスター',
#     'clashblaster_neo': 'クラッシュブラスターネオ',
#     'nova': 'ノヴァブラスター',
#     'nova_neo': 'ノヴァブラスターネオ',
#     'hotblaster': 'ホットブラスター',
#     'rapid': 'ラピッドブラスター',
#     'rapid_deco': 'ラピッドブラスターデコ',
#     'longblaster': 'ロングブラスター',
#     'h3reelgun': 'H3リールガン',
#     'h3reelgun_d': 'H3リールガンD',
#     'l3reelgun': 'L3リールガン',
#     'l3reelgun_d': 'L3リールガンD',
#     'quadhopper_black': 'クアッドホッパーブラック',
#     'quadhopper_white': 'クアッドホッパーホワイト',
#     'kelvin525': 'ケルビン525',
#     'sputtery': 'スパッタリー',
#     'sputtery_hue': 'スパッタリー・ヒュー',
#     'maneuver': 'スプラマニューバー',
#     'dualsweeper': 'デュアルスイーパー',
#     'dualsweeper_custom': 'デュアルスイーパーカスタム',
#     'carbon': 'カーボンローラー',
#     'carbon_deco': 'カーボンローラーデコ',
#     'splatroller': 'スプラローラー',
#     'splatroller_collabo': 'スプラローラーコラボ',
#     'dynamo': 'ダイナモローラー',
#     'wideroller': 'ワイドローラー',
#     'wideroller_collabo': 'ワイドローラーコラボ',
#     'variableroller': 'ヴァリアブルローラー',
#     'pablo': 'パブロ',
#     'pablo_hue': 'パブロ・ヒュー',
#     'fincent': 'フィンセント',
#     'hokusai': 'ホクサイ',
#     'jimuwiper': 'ジムワイパー',
#     'drivewiper': 'ドライブワイパー',
#     'drivewiper_deco': 'ドライブワイパーデコ',
#     'liter4k_scope': '4Kスコープ',
#     'bamboo14mk1': '14式竹筒銃・甲',
#     'rpen_5h': 'R-PEN/5H',
#     'squiclean_a': 'スクイックリンα',
#     'splatscope': 'スプラスコープ',
#     'splatscope_collabo': 'スプラスコープコラボ',
#     'splatcharger': 'スプラチャージャー',
#     'splatcharger_collabo': 'スプラチャージャーコラボ',
#     'soytuber': 'ソイチューバー',
#     'liter4k': 'リッター4K',
#     'explosher': 'エクスプロッシャー',
#     'furo': 'オーバーフロッシャー',
#     'screwslosher': 'スクリュースロッシャー',
#     'bucketslosher': 'バケットスロッシャー',
#     'bucketslosher_deco': 'バケットスロッシャーデコ',
#     'hissen': 'ヒッセン',
#     'hissen_hue': 'ヒッセン・ヒュー',
#     'kugelschreiber': 'クーゲルシュライバー',
#     'splatspinner': 'スプラスピナー',
#     'splatspinner_collabo': 'スプラスピナーコラボ',
#     'nautilus47': 'ノーチラス47',
#     'hydra': 'ハイドラント',
#     'barrelspinner': 'バレルスピナー',
#     'barrelspinner_deco': 'バレルスピナーデコ',
#     'campingshelter': 'キャンピングシェルター',
#     'campingshelter_sorella': 'キャンピングシェルターソレーラ',
#     'spygadget': 'スパイガジェット',
#     'parashelter': 'パラシェルター',
#     'lact450': 'LACT-450',
#     'tristringer': 'トライストリンガー',
# }


weapon_dict = {
    '52gal': '.52ガロン',
    '96gal': '.96ガロン',
    # '96gal_deco': '.96ガロンデコ',
    'nzap85': 'N-ZAP85',
    # 'nzap89': 'N-ZAP89',
    'momiji': 'もみじシューター',
    'wakaba': 'わかばシューター',
    'sharp': 'シャープマーカー',
    # 'sharp_neo': 'シャープマーカーネオ',
    'jetsweeper': 'ジェットスイーパー',
    # 'jetsweeper_custom': 'ジェットスイーパーカスタム',
    'sshooter': 'スプラシューター',
    'sshooter_collabo': 'スプラシューターコラボ',
    'spaceshooter': 'スペースシューター',
    # 'spaceshooter_collabo': 'スペースシューターコラボ',
    # 'heroshooter_replica': 'ヒーローシューター レプリカ',
    'prime': 'プライムシューター',
    'prime_collabo': 'プライムシューターコラボ',
    'promodeler_mg': 'プロモデラーMG',
    'promodeler_rg': 'プロモデラーRG',
    'bottlegeyser': 'ボトルガイザー',
    'bold': 'ボールドマーカー',
    # 'bold_neo': 'ボールドマーカーネオ',
    'rapid_elite': 'Rブラスターエリート',
    # 'rapid_elite_deco': 'Rブラスターエリートデコ',
    # 'sblast92': 'S-BLAST92',
    'clashblaster': 'クラッシュブラスター',
    # 'clashblaster_neo': 'クラッシュブラスターネオ',
    'nova': 'ノヴァブラスター',
    'nova_neo': 'ノヴァブラスターネオ',
    'hotblaster': 'ホットブラスター',
    'rapid': 'ラピッドブラスター',
    # 'rapid_deco': 'ラピッドブラスターデコ',
    'longblaster': 'ロングブラスター',
    'h3reelgun': 'H3リールガン',
    # 'h3reelgun_d': 'H3リールガンD',
    'l3reelgun': 'L3リールガン',
    # 'l3reelgun_d': 'L3リールガンD',
    'quadhopper_black': 'クアッドホッパーブラック',
    # 'quadhopper_white': 'クアッドホッパーホワイト',
    'kelvin525': 'ケルビン525',
    'sputtery': 'スパッタリー',
    'sputtery_hue': 'スパッタリー・ヒュー',
    'maneuver': 'スプラマニューバー',
    'dualsweeper': 'デュアルスイーパー',
    # 'dualsweeper_custom': 'デュアルスイーパーカスタム',
    'carbon': 'カーボンローラー',
    'carbon_deco': 'カーボンローラーデコ',
    'splatroller': 'スプラローラー',
    # 'splatroller_collabo': 'スプラローラーコラボ',
    'dynamo': 'ダイナモローラー',
    'wideroller': 'ワイドローラー',
    # 'wideroller_collabo': 'ワイドローラーコラボ',
    'variableroller': 'ヴァリアブルローラー',
    'pablo': 'パブロ',
    'pablo_hue': 'パブロ・ヒュー',
    # 'fincent': 'フィンセント',
    'hokusai': 'ホクサイ',
    'jimuwiper': 'ジムワイパー',
    'drivewiper': 'ドライブワイパー',
    # 'drivewiper_deco': 'ドライブワイパーデコ',
    'liter4k_scope': '4Kスコープ',
    'bamboo14mk1': '14式竹筒銃・甲',
    'rpen_5h': 'R-PEN/5H',
    'squiclean_a': 'スクイックリンα',
    'splatscope': 'スプラスコープ',
    # 'splatscope_collabo': 'スプラスコープコラボ',
    'splatcharger': 'スプラチャージャー',
    # 'splatcharger_collabo': 'スプラチャージャーコラボ',
    'soytuber': 'ソイチューバー',
    'liter4k': 'リッター4K',
    'explosher': 'エクスプロッシャー',
    'furo': 'オーバーフロッシャー',
    'screwslosher': 'スクリュースロッシャー',
    'bucketslosher': 'バケットスロッシャー',
    'bucketslosher_deco': 'バケットスロッシャーデコ',
    'hissen': 'ヒッセン',
    # 'hissen_hue': 'ヒッセン・ヒュー',
    'kugelschreiber': 'クーゲルシュライバー',
    'splatspinner': 'スプラスピナー',
    'splatspinner_collabo': 'スプラスピナーコラボ',
    'nautilus47': 'ノーチラス47',
    'hydra': 'ハイドラント',
    'barrelspinner': 'バレルスピナー',
    # 'barrelspinner_deco': 'バレルスピナーデコ',
    'campingshelter': 'キャンピングシェルター',
    # 'campingshelter_sorella': 'キャンピングシェルターソレーラ',
    'spygadget': 'スパイガジェット',
    'parashelter': 'パラシェルター',
    'lact450': 'LACT-450',
    'tristringer': 'トライストリンガー',
}